# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
version: '3'
services:
    frontend:
       build: ./Frontend/Final_draft
       container_name: frontend_server
       ports: 
           - "3838:3838"
    backend:
       build: ./Backend
       container_name: backend_server
       ports: 
           - "5000:5000"

#docker-compose up --build
